


well_done_display = "\n          `-_-` \n" \
                      "          <-+->  \n" \
                      "        `-_-`-_-` \n" \
                      "       <--<-+->--> \n" \
                      "      `-_-`-_-`-_-` \n" \
                      "     <--+-<-+->-+--> \n" \
                      "    `-_-`-_-`-_-`-_-` \n" \
                      "  <-+-<-+-<-+->-+->-+->\n" \
                      "    `-_-`-_-`-_-`-_-` \n" \
                      "     <--+-<-+->-+--> \n" \
                      "      `-_-`-_-`-_-` \n" \
                      "       <--<-+->--> \n" \
                      "        `-_-`-_-` \n" \
                      "          <-+-> \n" \
                      "          `-_-`\n"





camel = """

                  ,,__
        ..  ..   / o._)                   .---.
       /--'/--\  \-'||        .----.    .'     '.
      /        \_/ / |      .'      '..'         '-.
    .'\  \__\  __.'.'     .'          i-._
      )\ |  )\ |      _.'
     // \\\ // \\\\
    ||_  \\\|_  \\\_
    '--' '--'' '--'

"""

scorpion = """

          ___    ___
         ( _<    >_ )
         //        \\\\
         \\\\___..___//
          `-(    )-'
            _|__|_
           /_|__|_\\
           /_|__|_\\
           /_\__/_\\
            \ || /  _)
              ||   ( )
              \\\\___//
               `---'

"""

wolf = """
        
                                    .d$$b
                                  .' TO$;\\
                                 /  : TP._;
                                / _.;  :Tb|
                               /   /   ;j$j
                           _.-"       d$$$$
                         .' ..       d$$$$;
                        /  /P'      d$$$$P. |\\
                       /   "      .d$$$P' |\^"l
                     .'           `T$P^"'"'"  :
                 ._.'      _.'                ;
              `-.-".-'-' ._.       _.-"    .-"
            `.-" _____  ._              .-"
           -(.g$$$$$$$b.              .'
             ""^^T$$$P^)            .(:
               _/  -"  /.'         /:/;
            ._.'-'`-'  ")/         /;/;
         `-.-"..--""   " /         /  ;
        .-" ..--""        -'          :
        ..--""--.-"         (\      .-(\\
          ..--""              `-\(\/;`
            _.                      :
                                    ;`-
                                   :\\
                                   ;
        
"""



random_animals = {
    1: camel,
    2: scorpion,
    3: wolf
}


spartan = """
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNNWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWXOdolcldOXWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXd:'.......;xXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNx'     ......lKWWWMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXo........';,'cKWWMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWW0l,'..,,.'';;'oNWWMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWW0c';c:,',,':,,OWWMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNkoc;,,,',',,'xWMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMNKNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNkllllc::;''..dWMMWMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMNkxXWMMMMMMMMMMMMMMMMMMMMMMMMMMM0lcodlllc:,'..dWWWWWMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMWXooKWMMMMMMMMMMMMMMMMMMMMMMMMMMKl,:lokd:,''';kkdOXWWMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMWKol0WMMMMMMMMMMMMMMMMMMMMMMMMWWk:;oKKkl,'ckKNo..;o0NWWMMMMMMMMMMMMMMMMMM
    MMMMMMMMW0ol0WMMMMMMMMMMMMMMMMMMMMMMMWWXOc:kOxc,:dO0Ox:...':xKWMMMMMMMMMMMMMMMMM
    MMMMMMMMWW0ll0WMMMMMMMMMMMMMMMMMMWXOdocc:,':l:;,.............,lONWMMWMMWMMMMMMMM
    MMMMMMMMWWW0lcOWMMMMMMMMMMMMMMMWKo:,'...'....,,'.....''........'ckXWMMWMMMMMMMMM
    MMMMMMMMMMMW0ocOWMMMMMMMMMMMMMW0c;cl:'',,'....''......,;;'.....''':o0WMMMMMMMMMM
    MMMMMMMMMMMMWKockWMWWMWWMMMMMWO:,;,'';cc::;,..,:::;;'. .',...''.'''';xNMMMMMMMMM
    MMMMMMMMMMMMMWKockNOddxKWMWMNx;,;'. ..;loloo;.,oddo:..,..,;'.......'',oXMMMMMMMM
    MMMMMMMMMMMMMMWKdcxklokKWWWNk;''.  ':..;:;coc;':olc'.:O0c....,;'...'',,dNMMMMMMM
    MMMMMMMMMMMMMMMWKo:cd0NKklcllxl. .lKKc':l:lxxxl,,;,..dWMNk;'co,.''',,;;;kWMMMMMM
    MMMMMMMMMMMMMMWNKd;':l:.. . .coodKWWWx,;::oxxxd:....lXWWWWNXO:..'''',,;'lXWMMMMM
    MMMMMMMMMMMWN0xlcc:,:;.  .,;lONWMMMMWx:;,;dkxko;'..,0MMMMMMMWk,'::;'..''lXMMMMMM
    MMMMMMMMMMMMMWNXXXOdo;,cd0XWMWWMMMMMKc,lodkkkkdc;'..kWMMMMMMMWk,'cl;. ..cKMMMMMM
    MMMMMMMMMMMMMMMMWWWXkcdNMMMMWWMMMMWMKl;oxkkkOOxo:.. ,OWWMMMMMWWk'.'.  ..:0MMMMMM
    MMMMMMMMMMMMMMMMMMMMWNWMMMMMMMMMMWMNkllllodxdc'...  .:OWMMMMMMMWk;'.   .;0MMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWXl.'...,;,:'....  ..:KMMMMMMMMWO,.. ..;0MMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNk' ......... ........xWMMMMMMMMW0;.. .;0MMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNx. ...  ...  ....... ,0MMMMMMMMMW0;...:0MMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWK:.....        ....    ;KMWMMMMMMMWKc..cKMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl. ...         .......  :KMWMMMMMMMWNd'cXMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk. ...           ......  .oNWWMMMMMWWWWXKWMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx:coolc:,.      .'',,;;;oOXWMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0OOkkxdoddxkOO0KX0kkOOdOWWMMWMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKkkOkkxOXNWMMMMMMWN0xxdclOWWMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo,:okkONWMMMMMMMMMMXl'''.'xNWMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXc...cxKWMMMMMMMMMMMWO;.....oXWMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk,...,ckXWMMMMMMMMMWWKl..,,;xXWMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNx'.''..;kWMMMMMMMMMMMNo,l0OloXMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNd,:c,. :XMMMMMMMMMWMMKc;xKkckWMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNx,;c'.,0MMMMMMMMWMMMWO::O0loNMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNx;::',kWMMMMMMMMMMMMWkcdKxl0MMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNd;ld:lNWMMMMMMMMMMMMWkck0okWMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXooOo:OWWMMMMMMMMMMMWNxo0xdNMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWk:cl,,ONWWMMMMMMMMMWWXdxko0MMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWXl.....'kWMMMMMMMMMMMMWO:,':0WMWMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWXl....'cxXMMMMMMMMMMMMMWK;...,kWWWMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOx;.,:lONMWWMMMMMMMMMMMMMWO;.',oKWMMWMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKkkxkXWWWMMMMMMMMMMMMMMMMMMW0c:oodKWMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMX00KXWMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
"""

wizard = """
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMMMMMMWWXKXWMWWMWWWMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWMWWMN0kxdodx0NWWWWMWMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNOdoodollcclxKWWWWMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNOdodollllllllclxXWWWMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0dooolllllllllllookNMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMMMMMMWNkodollllc::cllllooooOWMMMMMMMM
    MMMWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMMMMMWKdlxxolc:cc:,,;ccccclclOWMMMMMMM
    MMMWNXXNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0odkxollc;,,,'':lllc:;clckNWMMMMM
    MWXkolooOXNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWOlxkdllllcc;,''oKWWNNXkc:cckNMMMMM
    WKo:::c;;clkWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0oxOxolcc:;,,,'cKMMMMWWWO:ccdXWMMMM
    Wk::;,,:::;:d0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKdxkxxolll:,',,,xWMMMMMMWNx::oKMMMMM
    Mk,''''';;;;:OWMMMMMMMMMMMMMMMMMMMMMMMMMWWWXddkolllllc,,,,':0MMMMMMMMMNd::kWMMMM
    MKc,:kK0Ko',lKMMMMMMMMMMMMMMMMMMMMMMMMMMMWNkdkxllllll:,''''lXMMMMMMWWWXd::OWMMMM
    MWNXNWMWMK:.:OMMMMMMMMMMMMMMMMMMMMMMMMMMWW0dkkolllllc;,'',,oNMMMMWMWXkookXWMMMMM
    MMMMMMMMMWx,,dNMMMMMMMMMMMMMMMMMMMMMMMMMMXxxkdllllllc:,,','dWMMMMWWWNXNMMMMMMMMM
    MMMMMMMMMWXd,:0WMMMMMMMMMMMMMMMMMMMMMMMWNOodolllllllc:;,,,.oWMMMMMMWMMMMMMMMMMMM
    MMMMMMMMMWWXo;co0WMMMMMMMMMMMMMMMMWX0Oxoc:,''''....'.......'loxk0XNMMMMMWMMMMMMM
    MMMMMMMMMMWWXo;,lKWWMMMMMMWMWXOxoc;'......'......................,;coxOXWWWMMWMM
    MMMMMMMMMMMWWKc,:xNWMMMMWXkl:,........',,,'............................':okXWWMW
    MMMMMMMMMWMMWNl';l0WWMW0l,...........'''......;cllc:;,:c;'.........';;,''..,xNWW
    MMMMMMMMMMMMMWXo;;dNMMO,............',;loxkddkO00000klcONOc..........,,,'...,KMW
    MMMMMMMMMMMMMMMKc,c0MMk'..........,cd0NWWW0dxxkOOOOkxlcOWMWO:........'.....;kWWW
    MMMMMMMMMMMMMMMWx,,xNWNk:'.......;dOXWWWWWXo:lddxxdc:o0WWWWWKo'.....'',:cdONMMWW
    MMMMMMMMMMMMMMMWK:'lKMWMNKkddodxkxdONWWWMWWXxll:::co0WWMWWNX0kxk0000KXNWMMWWMMMW
    MMMMMMMMMMMMMMMMNOc,xWMMMMMMMMMMKxOXWMWMMMMWWWKkdx0NWMMMWNOOXkkWMMWWWMMMMMMMMMMM
    MMMMMMMMMMMMMMMMWWx'cKWMMMMMMMWXOdxXWWNWMMWWWMWNNNWWWMWWWWkx0dkWWWWMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMWW0;'dKNMMMMMMN0xkO0KxkNWWMNNMWNXNNXXWWNX0OXKooxONWWMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMNKxoldodKWMMMMW0oddxdlxXWWWWWWMWNNNXNWWNWWWX0dlooxXWMWMMMMMMMMMM
    MMMMMMMMMMMMMMMWOoxxdxl;lKMMMW0l;oO0OxkKXKNMMMMMMWNNMWXNNNXKkccldddKWMMMMMMMMMMM
    MMMMMMMMMMMMMMMNdcxkxdl::kNWNOc:d0XNKKNXK0KNNNWMWXXWWWKO0KKOxolclodoOWMMMMMMMMMM
    MMMMMMMMMMMMMMMMkldxxxl;,;lolc;:dxOXXKKKKKKXK0KNXNWWWWKdd00od0d;cloolkWMMMMMMMMM
    MMMMMMMMMMMMMMMM0dxkxxc;::cl;;cc:lxoOXKXNXKXWX0KKKXWMNOkKXOx0x;,:clxxlOWMMMMMMMM
    MMMMMMMMMMWMMMMMN0Odc;'..'clc;:lc:''o0KK0KNXNWWXXKKNWWXNWKOXXl';;;clddoONMWWMMMM
    MMMMMMMMMWWMMMMMWWNl.... 'lllccc;,';lkKOkk0NNWWWWMMMMWXXKk0Nd'',;;;:loxdxXWWWWWM
    MMMMMMMMMMMMMMMMWWXc.....,lllc;,cd::dkxkXXXNWNXKXNWMWN0OkOXO;,lc';;:clodllkXWWWW
    MMMMMMWMMMMMMMMMMMNl.....;c:;,;xXk;cddlok0O0NKKK00XWN0k00xd;,,d0:';::::cllllONWW
    MMMMMMMMMMMMMMMMMMW0;...',:clxXWWd,cddoc:cccx0KXNNNWXO0Nx;,,;,lX0:';;;;:clc:dNWW
    MMMMMMMMMMMMMMMMMMWWKxl;'oKNWMMWNo:loddlll:::dKXKNWNNxlo:,;;;,:0WO;.';;;;;:xNWWM
    MMMMMMMMMMMMMMMMMMMMWWKc.dNWMMMMKlcllloxxocclcokdoxk0l;;;;;;;;,xWWKo,;:clodKWMWM
    MMMMMMMMMMMMMMMMWMMWWMK:.lXWMMMMOclolcoxxxollllclc:cllc:;;;;;;,cKWWWOdkOOOxxXMMM
    MMMMMMMMMMMMMMMMMMMMMMWx';OMMMMNd:oddccllllllllllllllc:;;;;;;;,,xWWWklddkl;oXWWM
    MMMMMMMMMMMMMMMMMMMMMMMXl.dWWMM0lodddllllllllllllllllc:;;;;;;;;,:0WNxcooocdXWWMM
    MMMMMMMMMMMMMMMMMMMMMMMWx';0WWWdcxdodollllllllllllllllc:;;;;;;;;,lXNOkxoxKWWWMMM
    MMMMMMMMMMMMMMMMMMMMMMMWd,,dNM0:lxolllllllllllllllllllc:;;;;;;;;;,xWWWNXWWWMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMWx,,:ONo:dollllllllllllllllllllc;;;;;;;;,,;dNWWMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMM0:,,d0c;lclllllllllllllllllllc:;;;;,;:ldOXWMWWMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMWd;,lXKOxddolcccc:::ccc:::;;;;;clodxOXWMWMMMMMWMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMWWk:'cXWMMWWWNK000xc;lxOOOkl:oOXNWWWMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMW0c'cKWWWMMMMWWKxo,;:oKWXdoc,cKWWWWWMMWWMWMWWWMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMM0c'',ldxxoloddo:''....'l,.....;lodoodxkxdkxodXMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMWXo.'........,,''...... ....................'xNWMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMWWX:,,.lxxkO0KKK00OxddlllllodokO0000OxdoooxkKWWWMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMWNd::oXWMMMWMMMMMMMMMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMNXKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
"""


ninja = """
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMWXOxdddOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMNWMMMMMMMMMMMMMMMMWO:......;xNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMNKOKWMMMMMMMMMMMMMMMXc....... .kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMW0olxKXWMMMMMMMMMMMMM0;.... .. .dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMWKdodd0WMMMMMMMMMMMMMK:..,::;;,,kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMW0l;,dWMMMMMWWNXNWWWXl...,,,'.cKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMWWX:  .kWWX0xl:,,,;;;;.....   .dNWWMMMMMWWMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMM0;    ;o:'.  ... ..  .....    .;lOXWMMMWWMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMWXc            .......             .,lONWWMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMNx,.         ........  .      .      .:xXWMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMXd;.        ...... . ..            ...,o0NWWMMWWMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMWNOxddddoolc;.......  ...         ......;xKNMWWMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMWWWWMMMMMMNO:... ......       ......   .':kNWWWNWMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMWMMMMMO, .......     .'.......   ....lKKOOKNMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO,....... .   .dX0d;.    .....'oxddxk0XWMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMx...  ..      ;XMMWN0xc;..... .cxOKXNNNWWMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMWWKd,.... .      .lNMMMMMMMN0xc..  :XWWMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMWWNk:'.........   ...,o0NWWWMMMWWWKxcdXMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMWXk;.....................:xKWWWWWMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMNx,......  .................,o0NWWMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMWKc. .....       ....          ..l0WMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMWO, .....              .           .xNMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMM0,   ..     .':cclc:;,'.    .....   .:ONMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMWo..   .  .,o0NWMMMMWWNXOd:. ....      'xNMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMWKc.  .  ,kNMMMMMMMMMMMMWWW0o;....      :XMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMNx,.   .oNMMMMMMMMMMMMWMMMWNOc.       :XMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMWMXd'   .xWMMMMMMMMMMMMMMMMMMW0dc;. . .lNMWMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMW0:.  'xWMMMMMMMMMMMMMMMMMMMWWNx' ...oNMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMXc.  ,KMMMMMMMMMMMMMMMMMMMMMWWO:.  .dNMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMWKk:.  ,0MMMMMMMMMMMMMMMMMMMMMMWWNo.. 'OMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMWKo;....';oXWWWWWWWWWWWWWWWWWWMMMMMMMWO,. :XMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMW0l:coxOKNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWk' .kMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWMWWWWWWWWWWWWWWWWWWWWWNNO;..lNMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMWMMWWMMMMMMMMMMMMWWWWWWWWWWWWWWWWWNNN0c. .dWMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWx'..:KMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0kk0WMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
"""

hero_types = {
    1: spartan,
    2: wizard,
    3: ninja
}



crab = """
    NNNWWWWWWWWWWWWWWWWWWWWWWNXKKXWWWWWWMWWMMWWMWWWWWWXKKXNWWWWWWWWWWWWWWWWWWWWWWWNN
    NNWWWWWWWWWWWWWWWWWWWKkl;'.,lOWWWWWWMWWMMWWMWWWWWNOl,.';lkKWWWWWWWWWWWWWWWWWWWWW
    WWWWWWWWWWWWWWWWWWW0l.   .cOWWWWOlkWWWWMMMWWWklONWWN0c.   .l0WWWWWWWWWWWWWWWWWWW
    WWWWWWWWWWWWWWWWWWk.    .xNWWNkc. lWMWWMMMMMWo .cOXWWNx.    .kWWWWWWWWWWWWWWWWWW
    WWWWWWWWWWWWWWWWW0:    .:kOdl,.  .kWMMMMMMMMWk.  .,ldOk:.    :0WMWWWWWWWWWWWWWWW
    WWWWWWWWWWWWWWWMO'              .lNWWMMMMMMWWNl.              'OWWWWWWWWWWWWWWWW
    WWWWWWWWWWWWWWMWo              .oNMMMWMMMMMMMWNd.              oWWWWWWWWWWWWWWWW
    WWWWWWWWWWWWWMMXc            .:OWMMMMMMMMMWMMMMWO:.            cXWWWWWWWWWWWWWWW
    WWWWWWWWWWWMMWMx.       ..':o0WMWWMWNNNNNNXNMMWWMW0d:'..       .xMWWWWWWWWWWWWWW
    WWWWWWWWMWMWWWM0'     ,x0KNWMWMNKkoc:,,,,,,:cokKNMWMWNK0x;.    'OWWWWWWWWWWWWWWW
    WWWWWWWWMWWMWNWWx.    ,KMWWMNkc,.              .,ckNMWWMK,    .dWNNWMWWWWWWWWWWW
    WWWWWWWWWWWM0o0WNk;.  .kWWKd,                      ,dKWWk.  .;kNW0o0WWWWWWWWWWWW
    WWWWWWWWWWWMd.oWWMNk;. .kk'                          'kk. .;xNWWWo.dMWWWWWWWWWWW
    WWWWWWWWWWWMk..dNWWWN0dcl;                            ,lcd0NWWWNd..kWWWMMWWWWWWW
    WWWWWWWMWWWWNx..,lkKKK0kd,                            ,dk0KXKkl,.'xNWWWWWWWWWWWW
    WWWWWWWWWKk0NNOc....',;'.;,                          ,;.';,'....cOWN0xKWWWWWWWWW
    WWWWWWWWWNo';oO0Oxdo:;'.,00;                        ;K0;.';:oddO0Od;'oXWWWWWWWWW
    WWWWWWWWWWNkc,......  .;oddl,.                     ,lddo;. .......,ckNWWWWWWWWWW
    WWWWWWWWWWWWWXklc::od:......,l:.                .:c,......;doc:clxXWWMWWWWWWWWWW
    WWWWWWWWWWWWWWMWWWWO, .:;..:ONWXkl;..      .';lkXWNO:..;:. ,OWWWMWWWWWWWWWWWWWWW
    WWWWWWWWWWWWWWWWWWX; .dd..dNWWMMMMWXK0OOOO0KNWMMMMWWNd..dd. ;KMMWMWWWWWWWWWWWWWW
    WWWWWWWWWWWWWWWWWW0,.oK: ,KWWWWMMMMMMMMMMMMMMMMMMMMWWK; :Kd.,0WWWWWWWWWWWWWWWWWW
    WWWWWWWWWWWWWWWWWWX;.kWk.'0WWWMMMMMMMMMMMMMMMMMMWWMWW0'.xWO.;KWWWWWWWWWWWWWWWWWW
    WWWWWWWWWWWWWWWWWWW0ckWNx,:KWWWWMMMMMMMMMMMMMMMMMWWWKc,xNWOlOWWWWWWWWWWWWWWWWWWW
    NNWWWWWWWWWWWWWWWWWWNNWWWXOKWWWWWWWWWWWWWWWWWWWWWWWWKOXWWWNNWWWWWWWWWWWWWWWWWWWN
"""



spider = """
    NNNNNNNNNNNNNNWWWWNNNWWWNNWWNWWWWWNWWWWWWWWWWWWWWNNWNNNNNNNNNNNNNNNNNNNNNNNNNNNN
    NNNNNNNNWNNNNWWWWNNNNNNNWWNWXkkOKXNWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNN
    WWWWWNNWWNWWWWNNXNNNNWWWWWNWNKkoc:lx0NWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNN
    WWWWNNWWWNXKOxolcccloddxkO0KXNWNOl,,cONWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNN
    WWWNNX0Oxdolooolcc:;;,,,',;;coOXNOc;,c0WWWWWWWWWWWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
    WXOxxxxxk0KXNNNNXXKKOkdoc;;,'..cKNk:,,oKWWWWWWWNXkoc:c::;;;;;:cloodxkO0KKKK00kxd
    WNXKXNWWWWWNNWWWWWWWWNXK0Okl;...cXXd;,,o0XWWWWKd,...'',,:clllloddddoolloddddkKWW
    WWWWWWWWNWWNWWWWNKOxoc:::ccc;'...dN0:..,ckWWNk;........';ld0XNWWWWWWNNNNNXK00XWW
    WWWWWWWWNWWNWWN0o:,'.............:XK:..':kWNd'.  ....,''....:oOXNWWWWWWWWWWWWWWW
    WWWWWWWWWWWWWXx:,'''.'...........,Ox'..l0XWk'   .  ,xkoc;,'....,cxKNWWWWWWWWWMMM
    WWWWWWWWWWWWNO:,,,'''''...........;;..:KNXO:...   .ckkOOOxoc;,'...'ckXWWWWWWWMMM
    WWWWWWWWWWWWWx;,,,,,,'..............'';cl:,..,'. .....';lkKXOxoc;'..'c0WWWMWMMMM
    WWWWWWWWWWWWWKo;,,,,;,.....................'',.......','.,ckXWNKOdlc;';OWMMWMMMM
    WWWWWWWWWWWWWKo;,,,,;;;'............''''...''.........',;'..:xXWWWN0o;,:0WMWWMMM
    WWWWWWWWWWWXxc;cxOxoolc:;..........'',,,,,,,'........'cc;;,'..;dKWWWXx:,lKMMMMMM
    WWWWWWWWWNOl:lkKNWWNNNK00xc,......'..',,,'...........;kNOo:;,'..;dKWWNkc,dNMMMMM
    WWWWWWWNOocokKNWWWWWWWWN0xc'.....,;'............';;,,oXWWNKxl:;,'.:kXWNk::0MMMMM
    WWWWWW0dokKNWWWWWWWWWN0o;...',:ox00d;........,,;c::okXWWWWWWXOoc;,,;l0WNk:dNMMMM
    WWWNKxdOXWWWWWWWWWWWXx::loxk0XNWWWWNKxdddxd:,,;xKKKNWWWWWWWWWWNKkoc:,:xNNo:OMMMM
    NKOxxOXWWWWWWWWWWWWKo:l0NWWWWWWWWWWWWWWWWWKl;,lXWWWWWWWWWWWWWWWWWNKdc;;dX0:dWMMM
    OxkKNWWWWWWWWWWWWW0l:oKWWWWWWWWWWWWWWWWWWNx:,:OWWWWWWWWWWWWWWWWWWWWN0o:;oK0OWWMM
    NNWWWWWWWWWWWWWWWOlcdXWWWWWWWWWWWWWWWWWWW0l;;dNMWWWWWWWWWWWWWWWWMWWWWXkc;oXMMMMM
    WWWWWWWWWWWWWWWWOllkXWWWWWWWWWWWWWWWWWWX0d:;dXWWWWWWMWWWWWWWWWWWWWWWWWWKo:oXWMMM
    WWWMWWWWWWWWWWNxlxXWMWWMWWWWWWWWWWWWWMW0oc:xXWWWMWWMMMWWMMWWWWWMWWWWWWWWNkclKWMM
    WWWWWWWWWWWWWXdo0WWWMWWWWWWWWWWWWWWWWMXd:cxXMMMWWWWWWWWWMMMMMMMMMWWWWWWWMW0cc0WM
    WWWWWWWWWWWNOoxXWMWWMWWWWWWWWWWWWWWWWXdllkNWMMMMWMMMMMMMMMMMMMMMMMMMMMMMMMWKxOWM
    WWWWWWWWWNOdkKNWWWWMWWWMWWWWWWWMWWWWKdo0NWMWWMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWM
    WMMWWWMMW0OXWWWMWWWWWMWWWWWWWWWWWWMKodXWMWWMWWMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWM
    MMMMWMMWWWMWWWWWWWMMMMMMMMMMMMMMWW0oxNWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMWMMMWMMWWWWWWWMMMMMMMMMMMMMMWNkkNWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
"""


samurai = """
    MMMMMMMMMMMMMMMMMMMMMMMMMMWWMMMMMMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMWN0odKMWMMMWWWOodkXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMWWW0:oNWNKXWW0:oKXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMO:dKOxOK0coNMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMWWWNXx;cxdxo;l0NNWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMNOolxkxxxdxxxkkocokXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMW0o;,:ccc:;::;,;clkNWWMMMMMMWWMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMWKo.    .';:c,    .c0WWMMWMXxo0WMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMNd,'.    .:cokl.    .cONWWKxclONWMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMWk,,;..'..:odd:'',::;''oOd:o0NWMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMWKdc:..;cclollcccodo:. ..;xNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMWWWkc;lo:;clll,;clllooc::,'..xKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMWNXKd'.;;'.;cldl';dxoc'...';,',dXNNWMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMWWNNKko,.....'..'cdxxkkdc. .;''::cxKXNMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMWWNXOc..    .,::::lddxxlc:,lkc;:::;l0WMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMNXk'       .,:lodoldxddolo:',:;,,lKMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMNO:.       ..,':c,';ldoc::;'.,cl;lXWMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMWXd'...'... ..;c:;...,cc::ol.  ;o,'dNMWWMMMWWWWMMWWWWMMMMMMMMMMMM
    MMMMMMMMMMMMMWNK0x'.. .;l:...,:c:,,clloxOxc;'. ,;.'kNNNWWNNWWWWWNNWWMMMMMMMMMMMM
    MMMMMMMMMMMMMMWWXc.,.  .:l,...,c;:dxxxxOKx';ko,':cloxOOKXNWWWWWWMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMK;.,,',cdd:..  ..,odddollc''kX0xl::loxkOKXNWWWMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMK:.;lk0OOo'...','',,:c:.   ..oKXd,.;dxkXXNWMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMKc''dNOlc.  .,;cl:,;col;... .;x0Oc...,l0WWMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMM0;..:KKo,. ..;;;,.';;',:;,...,oO0O:   .:0WMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMXc,ldKNx'   'lol:,;::';dxl,'..:OO0x.   :XMWMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMKol0W0c'...;;;odlcc:..''''..,;xXNNd...lKWMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMWKkKK:.....:lll;'''',;;;:,...'dNWWNkc::kWMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMWXX0:    .':lc,..;ccllloo,   .xWMMMWNXOkKWMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMWWNOo.  .,',;. .';l:,;:c:'    ,ONWMMMMMWKx0WWMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMWWX0xc'.  .ld;.  .;odko,,c,     .cOXWMMMMMMWKx0WWMMMMMMMMMMMMMMMMMM
    MMMMMMMMMWWWX0kl.... .,od:.   ;c;cxo.'c;,.   ;dx0NWMMMMMMMXkONMMMMMMMMMMMMMMMMMM
    MMMMMMMMMWWWN0o,,'. ..,:'    .''....  .''.. .dOx0NWMMMMMMWWNkkXWMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMWXxc. .... .         .. .',;:c;:dxKWMMMMMMMMWWWNOxXWMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMN0Okl,''...'...  .'coc,:c'....''oNWMMMMMMMMMWMMW0xKWWWMMMMMMMMMMMM
    MMMMMMMMMMMMMMWWWWWK00l...   .ck0K0kd:;'    ..xWWMMMMMMMMMMMMWWKx0WWMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMWWNd.     :KNWWWX0l'...   .xNWMMMMMMMMMMMMMMMXkkNMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMWWWO;'..  oNWWWWXkl:'...  cKWMMMMMMMMMMMMMMMMMNkkXMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMWWXk:.'.  .dWMMMWXKOc     ,0WMWNK0KNMMMMMMMMMMMWWOxKWWMMMMMMMM
    MMMMMMMMMMMMMMMMMMWWKo,...  .kWWMMWNXO:    .dWMMWKdoxXWWMMMMMMMMMMWWKx0WMMMMMMMM
    MMMMMMMMMMMMMMMMMMMWNXO;   .cXWWMMMNXKl....cKWMMWX0O0NWWMMMMMMMMMMMMMKk0NMMMMMMM
    MMMMMMMMMMMMMMMMMMMMWXO:. .;OWWMMMWWX0d,...oXWMMMMMMMMMMMMMMMMMMMMMMMWNOkXWMMMMM
    MMMMMMMMMMMMMMMMMMMWWX0d;,:kXWWWWWWNKxc.   lKXNWMMMMMMWMMMMMMMMMMMMMMMMW0xKWMMMM
    MMMMMMMMMMMMMMMMMMMWNKx:..,kXNWNNNXKKk;   .:odKNXNWWMMWWMMMMMMMMMMMMMMMWWX0NWWMM
    MMMMMMMMMMMMMMMMMWXOko;.  'oOXNXNNKxxo'.   ,;;dOO0K00KXXNNWWMMMWWWWNNNNWWWWWWMMM
    MMMMMMMMMMMWMWWNX0d:'.    'lkKOkxxdc,'.    .,;loc;;cccooolccccldk00KKXNWWWMMMMMM
    MMMMMMWWNNX0Oxxo;'.        .'......        ..',''.........':lx0XWWMMMMMMMMMMMMMM
    MMMWMWXK0Okl;''...',,;,,,,....''';ccclddddodxdlc,..,:odxxOKNNNWWMMMMMMMMMMMMMMMM
    MMMWXK000OOOOkOO0KXNNX0OO00O0XNNNWWWWWMMMWWWNNXKOk0XNNWWMMMWWWMMMMMMMMMMMMMMMMMM
    MMMWNNWWMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWMWWWMMMMMMMMMMMMMMMMMMMMMMMMMMM
"""



dragon = """
    MMMMMMMMMMMMMMMMMMMMMMWWNXXXX0xOWMMMMNO0WWWMMMMWOx0XXXXNWWMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMNKkdl:;;;,''.,xNWX0OOddOOKWMMMNx,.'',;;;:ldkKNMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMWXxl,. ...... .coxOK0c'.,,',;l0MMMX0xoc. ...... .,lxXWMMMMMMMMMMMMM
    MMMMMMMMMMMNOd;.   .'.    .kWMMMXc. .'..  .c0MMMMMMWx.    ...   .;dONMMMMMMMMMMM
    MMMMMMMMMNOo:,.  ...      ;KMMMMK:..,do'....lNMMMMMMK;      ...  .,:oONMMMMMMMMM
    MMMMMMMN0o;,.   .'.  ..   ;XMMMMNd...dXx:,;:;OMMMMMMX;   ..  .'.   .,;o0WMMMMMMM
    MMMMMMXx:::;.  .'..';;.   .OMMMMMKl...cO0OddkKWMMMMMO.   .;;'..'.  .;:::xXMMMMMM
    MMMMMXdllc,.   ';''.. ..   ;0MMMMWKl' .';cxONMMMMMW0;   .. ..'';'   .,clldXMMMMM
    MMMWKxoc'      ',.   ,;.    'xXMMXo,.     ..cOWMWXx'    .;,   .,.      'coxKWMMM
    MMNxlc' .;c.   ....,c;.       :OOc...      ...cOOc       .:c,....   .c;. 'clxNMM
    MNxc' .ckx:...  .ckx;.:'       ..';dx,..'. .:l,..       ':.;xkc.  ...:xkc. 'cxNM
    NOl'.:kklcdO0l..lX0;:Od.'.     'oKNXOl..,. .lNKo'     .'.dO:;0Xl..l0Ooclkk:.'lON
    Nx'.d0xoONWKo,:OWK:,OX:.:',xc.,OXOdlc:..'. .oNWNO,.cx,':.:XO,:KWO:,oKWNOox0d.'xN
    0,,kKO0NN0kdd0WMW0oOWNo:OxkWW00WOcoxd,......,dXWWK0WWkxO:dNWOo0MMW0ddkKNN0OKk',0
    c,ONkdkOKKXWMMMMMWWMMMNXWWMMMMMM0c,'. ..';dc .lNMMMMMMWWXNMMMWWMMMMMWXKKOkdkNk,c
    'dXd.;kNMMMMMMMMMMMMMMMMMMMMMMMMMN0xddx0KNMK: 'OWMMMMMMMMMMMMMMMMMMMMMMMNk;.dXd'
    ;0k:dNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKxddxONWd.,0MMMMMMMMMMMMMMMMMMMMMMMMMMNd:k0;
    cKooNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx;cxdo:l0o'dWMMMMMMMMMMMMMMMMMMMMMMMMMMMNdoKc
    dKOKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMX:,0MMM0c:;oXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKOKo
    dXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk;;looc;cxXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXd
    dOMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOc'':ONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMOd
    KXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWOlx0XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXK
    WWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKoOWMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXdx0000NMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWOl;,;,lKK0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNKko:' .;o0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
"""


villains = {
    1: crab,
    2: spider,
    3: samurai,
    4: dragon
}

game_over = """
        MMMMMMMMMMMNKKKKKKKKKKNMMWXKKKKKKKKKXWNKKKKKKXWNKKKKKKKKKKKKKKKKKKKKNMMMMMMMMMMM
        MMMMMMMMMNk;':llllcl:.;xkl',cllllcc,'lc'.;lc,'oc';cc,..'ccllllllll:.:kNMMMMMMMMM
        MMMMMMMMMO''dK0ollo0Kd,  .cOXxlllxXO:. .'dWWO:..l0WNl  ;KWXxllllll;. .kMMMMMMMMM
        MMMMMMMMMk'dWWd    'cc'  ;KM0'   ,KM0, .'xMMWXOONWMWo  ;XM0,         'OMMMMMMMMM
        MMMMMMMMMk'oWWd  .cxOk:  ,KMKc...cXM0, .'xMWkckxcOMWo  ;XMXkooool.  ;ONMMMMMMMMM
        MMMMMMMMMk'dWWd   .xWMd. ;KMNkdddONM0, .'dMWo   .dWWo  ;XM0;.....   lNMMMMMMMMMM
        MMMMMMMMMk.,xX0lcclokXd. ,KM0,   ;KM0' .'dWWo    dWWo  ;XMXdcccccc;.'dXMMMMMMMMM
        MMMMMMMMMXx,.;cccc:..,'  .;c;.   .;c;.   'c:.    '::.  .;ccccccccc,  .kMMMMMMMMM
        MMMMMMMMMMWXx,.................'od,............:xc...................;OMMMMMMMMM
        MMMMMMMMMMWOl:::::::::dOo;::::d0xl:::;;;;::::::clc::::::::::::::::lOXXWMMMMMMMMM
        MMMMMMMMMKl.'ldoooodl'.,..lxl..,..lxl.  .:dxdoolllll'  .oxdollloo;.;xXWMMMMMMMMM
        MMMMMMMMMk'cKNk,..,kNKc  ,KM0'   ,KMK, .'xMWx'.......  ;XMK:...oXXd. ;0MMMMMMMMM
        MMMMMMMMMk'dWWd    oWWd  ,KM0'   ,KMK, .,xMWk:;;;;'    ;XMXo:::xNKl. .kMMMMMMMMM
        MMMMMMMMMk'oWWo    oWWd. .c0Xx,.,xX0c. .,xMW0ollll;.   ;XMXxlllkNO:. .kMMMMMMMMM
        MMMMMMMMMk'lNWx.  .dWNo   .'l0KkK0l.   .,xMWd.         ;XMO.   ;XM0' .kMMMMMMMMM
        MMMMMMMMM0;.;xkdoodkk:.  'xl''lkc.   ....l00kddddddo,  ,kKd.   ,kKd. .kMMMMMMMMM
        MMMMMMMMMWXd,.......    .dNW0l'.   .cOk:,...........    ..    ''...  .kMMMMMMMMM
        MMMMMMMMMMMMXxllllllllldKWMMMW0olloOWMMNXkllllllllllllllllllldKKdlllldXMMMMMMMMM
        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
"""